# Basic Information
title: "Deploy Project to Netlify" # A clear, concise title for your contribution
description: "Deploy this project to Netlify using the Netlify CLI. If needed, link it to a site or create a new one. Show the deployed site's URL when done. This prompt guides you through linking or initializing the site, then deploys it to a production URL." # 1-2 sentences explaining the purpose
type: Prompt # Must be one of: Prompt, Workflow, Notebook, Folder

# External Resources
link: "https://app.warp.dev/drive/prompt/Deploy-project-to-Netlify-qcHGGJNXd5ng0tY3AmOcMC" # URL to the original Warp Drive resource. Make sure that you have sharing for everyone available.

# Metadata
author: "hongyi-chen" # Your GitHub username in quotes
date_added: 2025-04-15 # Current date in YYYY-MM-DD format

# Classification -- these should all be in lowercase for consistency
tags:
  - deployment
  - netlify
  - web
